---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "../defaults.yml"

  tasks:
    - name: validate vars
      assert:
        that:
          - stack_name != ''
          - keyname != ''
          - region != ''
          - owner != ''

    - name: Create a stack for running restmail.net
      action: cloudformation
        state=present
        region="{{ region }}"
        stack_name="{{ stack_name }}"
        template="../templates/app.json"
      args:
        template_parameters:
          KeyName: "{{ keyname }}"
          StackName: "{{ stack_name }}"
          HostedZone: "{{ hosted_zone }}"
          FQDN: "{{ stack_name }}.dev.{{ hosted_zone }}"
      register: stack

    - debug: var=stack

    - name: add new host
      add_host: hostname={{ stack['stack_outputs']['EC2HostName'] }} groupname=whatevs

- name: Configure instance
  hosts: whatevs
  remote_user: ec2-user
  gather_facts: true
  vars_files:
    - "../defaults.yml"
  vars:
    public_hostname: "{{ hostvars['localhost']['stack']['stack_outputs']['PublicDNS'] }}"
    ec2_hostname: "{{ hostvars['localhost']['stack']['stack_outputs']['ECSHostName'] }}"
  roles:
    - common
    - team
    - nginx
    - redis
    - nodejs
    - restmail

